name = "FakeR"
uuid = "c5e85ae5-ee9c-4ab3-9a8b-9ba885715241"
authors = ["Thomas Poulsen"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
